-- Seed at least 30 realistic scenarios with balanced free/premium flags.

insert into public.scenarios (
  slug,
  title,
  category,
  difficulty,
  is_premium,
  is_active,
  estimated_minutes,
  description,
  prompt,
  rubric,
  follow_up_config,
  metadata
)
values
  (
    'intro-standup-update',
    'Daily Standup Update',
    'workplace-communication',
    'beginner',
    false,
    true,
    5,
    'Deliver a concise standup update covering progress, blockers, and next steps.',
    'You are speaking to your engineering team in a morning standup. Explain what you finished yesterday, what you plan today, and one blocker needing help.',
    '{"criteria":[{"name":"Clarity","weight":0.25,"anchors":{"excellent":"Message is concise and easy to follow","needs_work":"Rambling or unclear priorities"}},{"name":"Structure","weight":0.20,"anchors":{"excellent":"Covers yesterday/today/blocker in order","needs_work":"Misses one or more standup sections"}},{"name":"Specificity","weight":0.20,"anchors":{"excellent":"Uses concrete tasks and outcomes","needs_work":"Vague updates without evidence"}},{"name":"Ownership","weight":0.20,"anchors":{"excellent":"Clearly identifies blocker and ask","needs_work":"Blocker is implied but no explicit ask"}},{"name":"Delivery","weight":0.15,"anchors":{"excellent":"Confident pace and tone","needs_work":"Monotone or rushed delivery"}}],"scoring":{"min":0,"max":100,"passing":75}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["clarification","priority_tradeoff"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["standup","engineering","team"],"persona":"individual_contributor"}'::jsonb
  ),
  (
    'project-risk-escalation',
    'Escalate Project Risk',
    'leadership',
    'intermediate',
    true,
    true,
    8,
    'Escalate a schedule risk to leadership with options and recommendation.',
    'You have discovered a two-week delay risk in a cross-functional project. Brief your director with the impact, options, and your recommendation.',
    '{"criteria":[{"name":"Executive Summary","weight":0.2},{"name":"Risk Framing","weight":0.2},{"name":"Options with Tradeoffs","weight":0.25},{"name":"Recommendation Quality","weight":0.2},{"name":"Confidence","weight":0.15}],"scoring":{"min":0,"max":100,"passing":80}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["data_challenge","resource_constraint"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["risk","escalation","director"],"persona":"engineering_manager"}'::jsonb
  ),
  (
    'customer-discovery-call',
    'Customer Discovery Call',
    'sales',
    'beginner',
    false,
    true,
    7,
    'Run a discovery conversation to uncover pain points and priorities.',
    'Open a first call with a prospective customer, ask diagnostic questions, and summarize their main pains before proposing next steps.',
    '{"criteria":[{"name":"Rapport","weight":0.2},{"name":"Question Quality","weight":0.25},{"name":"Active Listening","weight":0.2},{"name":"Pain Clarification","weight":0.2},{"name":"Next Steps","weight":0.15}],"scoring":{"min":0,"max":100,"passing":72}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["objection","budget"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["discovery","saas","b2b"],"persona":"account_executive"}'::jsonb
  ),
  (
    'objection-handling-price',
    'Handle Pricing Objection',
    'sales',
    'intermediate',
    true,
    true,
    6,
    'Respond to a prospect who believes your solution is too expensive.',
    'A prospect says your price is 20% above a competitor. Respond by reframing value, quantifying ROI, and preserving trust.',
    '{"criteria":[{"name":"Empathy","weight":0.2},{"name":"Value Framing","weight":0.3},{"name":"ROI Quantification","weight":0.25},{"name":"Composure","weight":0.1},{"name":"Close for Next Step","weight":0.15}],"scoring":{"min":0,"max":100,"passing":78}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["competitor_compare","discount_request"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["objections","pricing","roi"],"persona":"account_executive"}'::jsonb
  ),
  (
    'incident-update-to-customers',
    'Incident Update to Customers',
    'customer-support',
    'intermediate',
    false,
    true,
    5,
    'Deliver a transparent update during an active service incident.',
    'A platform outage is ongoing. Provide a customer-facing update with known facts, mitigation steps, and next communication window.',
    '{"criteria":[{"name":"Transparency","weight":0.25},{"name":"Calm Tone","weight":0.2},{"name":"Actionability","weight":0.25},{"name":"Accountability","weight":0.15},{"name":"Timeliness","weight":0.15}],"scoring":{"min":0,"max":100,"passing":76}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["angry_customer","timeline_pressure"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["incident","status","support"],"persona":"support_manager"}'::jsonb
  ),
  (
    'performance-review-self-summary',
    'Performance Review Self-Summary',
    'career-growth',
    'beginner',
    false,
    true,
    6,
    'Summarize your impact for a performance review conversation.',
    'Present your top achievements, measurable outcomes, and development goals from the past half-year.',
    '{"criteria":[{"name":"Outcome Focus","weight":0.3},{"name":"Evidence","weight":0.25},{"name":"Reflection","weight":0.2},{"name":"Growth Plan","weight":0.15},{"name":"Delivery","weight":0.1}],"scoring":{"min":0,"max":100,"passing":73}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["calibration","promotion_readiness"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["review","impact","career"],"persona":"individual_contributor"}'::jsonb
  ),
  (
    'conflict-resolution-peer',
    'Resolve Conflict with Peer',
    'difficult-conversations',
    'intermediate',
    true,
    true,
    9,
    'Address recurring friction with a teammate while preserving relationship.',
    'You and a peer have disagreed publicly in meetings. Initiate a private conversation to align expectations and agree on a collaboration norm.',
    '{"criteria":[{"name":"Respectful Framing","weight":0.2},{"name":"Specific Examples","weight":0.2},{"name":"Shared Goal Orientation","weight":0.25},{"name":"Boundary Setting","weight":0.2},{"name":"Agreement Quality","weight":0.15}],"scoring":{"min":0,"max":100,"passing":79}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["defensive_response","manager_escalation"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["conflict","collaboration","feedback"],"persona":"cross_functional_partner"}'::jsonb
  ),
  (
    'executive-briefing-quarterly',
    'Quarterly Executive Briefing',
    'presentations',
    'advanced',
    true,
    true,
    10,
    'Present quarterly results and strategic recommendations to executives.',
    'Deliver a concise QBR-style briefing: outcomes, missed targets, root causes, and your next-quarter strategic bets.',
    '{"criteria":[{"name":"Narrative Arc","weight":0.2},{"name":"Business Acumen","weight":0.25},{"name":"Data Storytelling","weight":0.2},{"name":"Recommendation Strength","weight":0.2},{"name":"Executive Presence","weight":0.15}],"scoring":{"min":0,"max":100,"passing":82}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["assumption_test","budget_pushback","kpi_drilldown"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["qbr","exec","strategy"],"persona":"functional_lead"}'::jsonb
  ),
  (
    'new-manager-1on1',
    'First 1:1 as New Manager',
    'leadership',
    'beginner',
    false,
    true,
    6,
    'Lead your first one-on-one with a direct report.',
    'Run your first 1:1 with a new report: build trust, understand goals, and establish a working agreement.',
    '{"criteria":[{"name":"Psychological Safety","weight":0.25},{"name":"Question Depth","weight":0.2},{"name":"Expectations Clarity","weight":0.25},{"name":"Listening Signals","weight":0.15},{"name":"Action Plan","weight":0.15}],"scoring":{"min":0,"max":100,"passing":74}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["career_goal","concern_escalation"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["management","1on1","trust"],"persona":"new_manager"}'::jsonb
  ),
  (
    'stakeholder-alignment-kickoff',
    'Stakeholder Alignment Kickoff',
    'workplace-communication',
    'intermediate',
    true,
    true,
    8,
    'Align diverse stakeholders at the start of a cross-functional project.',
    'Open a kickoff meeting by clarifying goals, roles, risks, and decision cadence for product, design, and engineering.',
    '{"criteria":[{"name":"Goal Clarity","weight":0.25},{"name":"Role Definition","weight":0.2},{"name":"Risk Awareness","weight":0.2},{"name":"Facilitation","weight":0.2},{"name":"Decision Framing","weight":0.15}],"scoring":{"min":0,"max":100,"passing":77}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["scope_change","resource_gap"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["kickoff","alignment","cross-functional"],"persona":"product_manager"}'::jsonb
  ),
  (
    'technical-concept-nontechnical',
    'Explain Technical Concept to Non-Technical Audience',
    'presentations',
    'beginner',
    false,
    true,
    5,
    'Translate a technical idea into accessible language for business partners.',
    'Explain how feature flags reduce deployment risk to a non-technical operations team in plain language.',
    '{"criteria":[{"name":"Accessibility","weight":0.3},{"name":"Analogy Use","weight":0.2},{"name":"Accuracy","weight":0.2},{"name":"Brevity","weight":0.15},{"name":"Audience Fit","weight":0.15}],"scoring":{"min":0,"max":100,"passing":70}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["jargon_challenge","value_question"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["translation","communication","tech"],"persona":"engineer"}'::jsonb
  ),
  (
    'board-meeting-opening',
    'Open a Board Meeting Segment',
    'executive-communication',
    'advanced',
    true,
    true,
    9,
    'Open a board segment with confidence and clear strategic framing.',
    'You have five minutes to open the board discussion on product strategy and set decision context.',
    '{"criteria":[{"name":"Strategic Framing","weight":0.3},{"name":"Signal-to-Noise","weight":0.2},{"name":"Decision Clarity","weight":0.2},{"name":"Authority","weight":0.15},{"name":"Time Discipline","weight":0.15}],"scoring":{"min":0,"max":100,"passing":84}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["board_pushback","financial_scrutiny"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["board","strategy","leadership"],"persona":"vp_product"}'::jsonb
  ),
  (
    'networking-intro-conference',
    'Conference Networking Introduction',
    'networking',
    'beginner',
    false,
    true,
    4,
    'Give a strong personal introduction in a networking context.',
    'At a conference meetup, introduce yourself, your focus area, and a thoughtful question to continue the conversation.',
    '{"criteria":[{"name":"Conciseness","weight":0.2},{"name":"Memorability","weight":0.2},{"name":"Relevance","weight":0.2},{"name":"Question Craft","weight":0.2},{"name":"Warmth","weight":0.2}],"scoring":{"min":0,"max":100,"passing":68}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["awkward_pause","pivot_topic"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["conference","intro","relationship"],"persona":"professional"}'::jsonb
  ),
  (
    'media-interview-key-message',
    'Media Interview Key Message',
    'public-speaking',
    'advanced',
    true,
    true,
    8,
    'Keep key messages consistent under pressure in a media interview.',
    'A journalist asks difficult questions about a recent product issue. Respond with transparency while returning to key messages.',
    '{"criteria":[{"name":"Message Discipline","weight":0.3},{"name":"Bridging Technique","weight":0.2},{"name":"Composure","weight":0.2},{"name":"Credibility","weight":0.15},{"name":"Brevity","weight":0.15}],"scoring":{"min":0,"max":100,"passing":85}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["hostile_question","fact_check"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["media","messaging","reputation"],"persona":"spokesperson"}'::jsonb
  ),
  (
    'status-update-remote-team',
    'Remote Team Weekly Status Update',
    'workplace-communication',
    'beginner',
    false,
    true,
    5,
    'Provide a clear asynchronous style update to a distributed team.',
    'Deliver a spoken weekly update that remote teammates can quickly understand and act on.',
    '{"criteria":[{"name":"Organization","weight":0.25},{"name":"Action Orientation","weight":0.25},{"name":"Clarity","weight":0.2},{"name":"Tone","weight":0.15},{"name":"Time Awareness","weight":0.15}],"scoring":{"min":0,"max":100,"passing":72}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["dependency_question","priority_shift"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["remote","status","team"],"persona":"project_lead"}'::jsonb
  ),
  (
    'mentor-feedback-conversation',
    'Give Constructive Mentoring Feedback',
    'coaching',
    'intermediate',
    true,
    true,
    7,
    'Provide balanced and actionable feedback to a mentee.',
    'Your mentee missed stakeholder expectations on a demo. Give feedback using specific examples and a development plan.',
    '{"criteria":[{"name":"Balance","weight":0.2},{"name":"Specificity","weight":0.25},{"name":"Actionability","weight":0.25},{"name":"Empathy","weight":0.15},{"name":"Follow-through","weight":0.15}],"scoring":{"min":0,"max":100,"passing":78}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["pushback","confidence_drop"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["mentoring","feedback","growth"],"persona":"mentor"}'::jsonb
  ),
  (
    'sprint-retro-facilitation',
    'Facilitate Sprint Retrospective',
    'facilitation',
    'intermediate',
    false,
    true,
    7,
    'Facilitate a retrospective that surfaces learning and commitments.',
    'Guide a team retrospective after a tough sprint, ensuring balanced participation and concrete action items.',
    '{"criteria":[{"name":"Inclusion","weight":0.2},{"name":"Root-Cause Depth","weight":0.25},{"name":"Neutral Facilitation","weight":0.2},{"name":"Action Commitments","weight":0.25},{"name":"Timeboxing","weight":0.1}],"scoring":{"min":0,"max":100,"passing":75}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["dominant_voice","blame_dynamic"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["retrospective","agile","facilitation"],"persona":"scrum_master"}'::jsonb
  ),
  (
    'change-announcement-reorg',
    'Announce Team Reorganization',
    'leadership',
    'advanced',
    true,
    true,
    8,
    'Communicate a sensitive organizational change with empathy and clarity.',
    'Announce a reorganization affecting reporting lines while addressing uncertainty and maintaining trust.',
    '{"criteria":[{"name":"Empathy","weight":0.25},{"name":"Clarity of What/Why","weight":0.25},{"name":"Support Signals","weight":0.2},{"name":"Q&A Readiness","weight":0.2},{"name":"Steadiness","weight":0.1}],"scoring":{"min":0,"max":100,"passing":83}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["job_security_question","timeline_uncertainty"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["change","reorg","leadership"],"persona":"department_head"}'::jsonb
  ),
  (
    'client-qbr-renewal',
    'Client QBR for Renewal',
    'customer-success',
    'intermediate',
    false,
    true,
    8,
    'Run a value-focused quarterly review aimed at renewal.',
    'Present ROI, adoption trends, and next-quarter success plan to secure confidence before renewal.',
    '{"criteria":[{"name":"Outcome Story","weight":0.3},{"name":"Data Credibility","weight":0.2},{"name":"Risk Identification","weight":0.2},{"name":"Success Plan","weight":0.2},{"name":"Relationship Management","weight":0.1}],"scoring":{"min":0,"max":100,"passing":77}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["budget_cut","stakeholder_turnover"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["qbr","renewal","customer_success"],"persona":"csm"}'::jsonb
  ),
  (
    'storytelling-product-vision',
    'Tell a Product Vision Story',
    'storytelling',
    'advanced',
    true,
    true,
    9,
    'Inspire a team with a compelling and grounded product vision narrative.',
    'Share a 12-month product vision that connects customer pain, market shifts, and execution milestones.',
    '{"criteria":[{"name":"Narrative Cohesion","weight":0.25},{"name":"Customer Grounding","weight":0.2},{"name":"Strategic Differentiation","weight":0.25},{"name":"Inspiration","weight":0.15},{"name":"Execution Link","weight":0.15}],"scoring":{"min":0,"max":100,"passing":84}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["feasibility_challenge","priority_conflict"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["vision","narrative","product"],"persona":"product_leader"}'::jsonb
  ),
  (
    'salary-negotiation-discussion',
    'Salary Negotiation Discussion',
    'career-growth',
    'intermediate',
    false,
    true,
    6,
    'Negotiate compensation professionally with evidence and flexibility.',
    'Discuss your compensation adjustment request with your manager using market data and performance impact.',
    '{"criteria":[{"name":"Preparation Evidence","weight":0.25},{"name":"Professional Tone","weight":0.2},{"name":"Value Articulation","weight":0.25},{"name":"Flexibility","weight":0.15},{"name":"Close","weight":0.15}],"scoring":{"min":0,"max":100,"passing":76}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["budget_constraint","delay_response"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["negotiation","compensation","career"],"persona":"employee"}'::jsonb
  ),
  (
    'handling-hostile-audience-question',
    'Handle Hostile Audience Question',
    'public-speaking',
    'advanced',
    true,
    true,
    7,
    'Respond to a hostile question while maintaining control and credibility.',
    'During a town hall, an audience member challenges your integrity. Respond calmly and redirect to constructive dialogue.',
    '{"criteria":[{"name":"Emotional Regulation","weight":0.25},{"name":"Respectful Response","weight":0.2},{"name":"Fact-based Clarification","weight":0.25},{"name":"Room Control","weight":0.15},{"name":"Message Recovery","weight":0.15}],"scoring":{"min":0,"max":100,"passing":86}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["repeat_attack","audience_polarization"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["townhall","qanda","pressure"],"persona":"leader"}'::jsonb
  ),
  (
    'new-feature-demo',
    'Demo a New Product Feature',
    'presentations',
    'beginner',
    false,
    true,
    6,
    'Deliver a customer-centric feature demo with clear flow and value.',
    'Demo a new collaboration feature to prospective users, focusing on pain solved and workflow improvements.',
    '{"criteria":[{"name":"Use-case Framing","weight":0.25},{"name":"Flow Clarity","weight":0.25},{"name":"Benefit Translation","weight":0.25},{"name":"Pacing","weight":0.15},{"name":"Call to Action","weight":0.1}],"scoring":{"min":0,"max":100,"passing":71}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["integration_question","security_concern"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["demo","feature","product_marketing"],"persona":"solutions_engineer"}'::jsonb
  ),
  (
    'stakeholder-no-saying',
    'Say No to a Stakeholder Request',
    'difficult-conversations',
    'intermediate',
    true,
    true,
    6,
    'Decline a request while preserving trust and offering alternatives.',
    'A senior stakeholder asks for an out-of-scope feature this sprint. Decline, explain tradeoffs, and propose options.',
    '{"criteria":[{"name":"Respect","weight":0.2},{"name":"Tradeoff Clarity","weight":0.25},{"name":"Alternative Paths","weight":0.25},{"name":"Boundary Strength","weight":0.15},{"name":"Relationship Management","weight":0.15}],"scoring":{"min":0,"max":100,"passing":79}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["executive_pressure","scope_creep"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["prioritization","stakeholder","boundaries"],"persona":"product_manager"}'::jsonb
  ),
  (
    'on-call-handoff',
    'On-call Incident Handoff',
    'workplace-communication',
    'beginner',
    false,
    true,
    4,
    'Handoff operational context clearly between engineers.',
    'You are ending your on-call shift. Brief the incoming engineer on incident status, risks, and next checks.',
    '{"criteria":[{"name":"Completeness","weight":0.3},{"name":"Prioritization","weight":0.2},{"name":"Brevity","weight":0.2},{"name":"Risk Flagging","weight":0.2},{"name":"Actionable Next Steps","weight":0.1}],"scoring":{"min":0,"max":100,"passing":70}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["unknown_root_cause","escalation_threshold"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["oncall","handoff","incident"],"persona":"engineer"}'::jsonb
  ),
  (
    'training-session-facilitator',
    'Facilitate Internal Training Session',
    'facilitation',
    'intermediate',
    false,
    true,
    8,
    'Lead a practical training session that keeps participants engaged.',
    'Open an internal training on secure coding practices and maintain engagement while pacing content for mixed experience levels.',
    '{"criteria":[{"name":"Learning Objectives","weight":0.2},{"name":"Engagement Techniques","weight":0.25},{"name":"Clarity of Examples","weight":0.2},{"name":"Pacing","weight":0.2},{"name":"Knowledge Checks","weight":0.15}],"scoring":{"min":0,"max":100,"passing":74}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["time_overrun","novice_question"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["training","enablement","facilitation"],"persona":"team_lead"}'::jsonb
  ),
  (
    'cross-cultural-client-call',
    'Cross-Cultural Client Call',
    'customer-success',
    'intermediate',
    true,
    true,
    7,
    'Adapt communication style for a global customer meeting.',
    'Lead a call with a client team from a different communication culture and align on project expectations respectfully.',
    '{"criteria":[{"name":"Cultural Sensitivity","weight":0.25},{"name":"Clarity","weight":0.2},{"name":"Pacing and Pauses","weight":0.2},{"name":"Alignment Checks","weight":0.2},{"name":"Relationship Signals","weight":0.15}],"scoring":{"min":0,"max":100,"passing":80}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["misunderstanding","indirect_feedback"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["global","client","communication"],"persona":"consultant"}'::jsonb
  ),
  (
    'delegation-conversation',
    'Delegate a Critical Task',
    'leadership',
    'beginner',
    false,
    true,
    5,
    'Delegate a task with clear ownership and support boundaries.',
    'Delegate a high-visibility deliverable to a teammate, clarifying outcomes, checkpoints, and available support.',
    '{"criteria":[{"name":"Outcome Definition","weight":0.25},{"name":"Ownership Clarity","weight":0.25},{"name":"Support Framing","weight":0.2},{"name":"Timeline","weight":0.15},{"name":"Empowerment Tone","weight":0.15}],"scoring":{"min":0,"max":100,"passing":72}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["capacity_concern","quality_risk"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["delegation","ownership","management"],"persona":"manager"}'::jsonb
  ),
  (
    'executive-email-readout-spoken',
    'Spoken Executive Readout',
    'executive-communication',
    'advanced',
    true,
    true,
    6,
    'Give a spoken readout equivalent to an executive summary email.',
    'Provide a two-minute spoken readout on launch readiness, risks, and asks for VP review.',
    '{"criteria":[{"name":"Topline Clarity","weight":0.3},{"name":"Decision Orientation","weight":0.25},{"name":"Risk Precision","weight":0.2},{"name":"Conciseness","weight":0.15},{"name":"Confidence","weight":0.1}],"scoring":{"min":0,"max":100,"passing":85}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["what_changed","ask_justification"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["exec","readout","launch"],"persona":"program_manager"}'::jsonb
  ),
  (
    'intro-story-brand-yourself',
    'Personal Brand Intro Story',
    'storytelling',
    'beginner',
    false,
    true,
    5,
    'Tell a brief personal narrative that communicates professional identity.',
    'Share a 90-second story about your background, strengths, and the kind of problems you love solving.',
    '{"criteria":[{"name":"Authenticity","weight":0.25},{"name":"Structure","weight":0.2},{"name":"Memorable Hook","weight":0.2},{"name":"Relevance","weight":0.2},{"name":"Brevity","weight":0.15}],"scoring":{"min":0,"max":100,"passing":69}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["clarify_strength","audience_shift"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["brand","intro","narrative"],"persona":"professional"}'::jsonb
  ),
  (
    'renewal-risk-call',
    'Renewal Risk Rescue Call',
    'customer-success',
    'advanced',
    true,
    true,
    9,
    'Recover a high-risk account with clear accountability and plan.',
    'A customer is considering churn due to low adoption. Run a rescue call with root causes, commitments, and success milestones.',
    '{"criteria":[{"name":"Accountability","weight":0.2},{"name":"Diagnosis Depth","weight":0.25},{"name":"Recovery Plan","weight":0.25},{"name":"Stakeholder Management","weight":0.15},{"name":"Confidence","weight":0.15}],"scoring":{"min":0,"max":100,"passing":84}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["escalation","timeline_demand"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["renewal","churn","rescue"],"persona":"senior_csm"}'::jsonb
  ),
  (
    'product-launch-all-hands',
    'Product Launch All-Hands',
    'public-speaking',
    'intermediate',
    false,
    true,
    7,
    'Present a launch narrative that energizes internal teams.',
    'Announce an important product launch at all-hands, connecting customer value and team contributions.',
    '{"criteria":[{"name":"Energy","weight":0.2},{"name":"Narrative Clarity","weight":0.25},{"name":"Customer Value","weight":0.2},{"name":"Recognition","weight":0.2},{"name":"Call to Action","weight":0.15}],"scoring":{"min":0,"max":100,"passing":75}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":2,"question_types":["timeline_slip","competitive_question"],"adaptive_difficulty":false}'::jsonb,
    '{"tags":["launch","allhands","announcement"],"persona":"product_marketer"}'::jsonb
  ),
  (
    'difficult-feedback-upward',
    'Give Upward Feedback to Manager',
    'difficult-conversations',
    'advanced',
    true,
    true,
    8,
    'Deliver candid upward feedback constructively and professionally.',
    'Share feedback with your manager about frequent late requirement changes that impact team stress and delivery.',
    '{"criteria":[{"name":"Respectful Candor","weight":0.25},{"name":"Evidence Quality","weight":0.2},{"name":"Impact Framing","weight":0.25},{"name":"Solution Orientation","weight":0.2},{"name":"Composure","weight":0.1}],"scoring":{"min":0,"max":100,"passing":85}}'::jsonb,
    '{"follow_up_enabled":true,"max_questions":3,"question_types":["defensive_manager","retaliation_concern"],"adaptive_difficulty":true}'::jsonb,
    '{"tags":["upward_feedback","management","candor"],"persona":"senior_ic"}'::jsonb
  )
on conflict (slug) do update
set
  title = excluded.title,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_premium = excluded.is_premium,
  is_active = excluded.is_active,
  estimated_minutes = excluded.estimated_minutes,
  description = excluded.description,
  prompt = excluded.prompt,
  rubric = excluded.rubric,
  follow_up_config = excluded.follow_up_config,
  metadata = excluded.metadata,
  updated_at = timezone('utc', now());
